name: check

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v4
      - name: install dotfiles
        run: ./install.sh
      - name: check neovim
        run: nvim --version
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run shellcheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC1090 -e SC2148 -e SC1071 -e SC1091
      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dotfiles
        run: sudo ./install.sh
      # - name: install time
      #   run: sudo apt install -y time
      - name: run bench
        run: ./bench.sh > result.json
      - name: print result
        run: cat result.json
      - name: upload benchmark
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: customSmallerIsBetter
          output-file-path: result.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
